name: GitHub Classroom Workflow

on: [push]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 25
        uses: actions/setup-java@v3
        with:
          java-version: '25'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
          
      - name: Create classroom directory
        run: mkdir -p .github/classroom
        
      - name: Build and Generate autograding.json
        run: mvn clean test-compile exec:java@generate-autograding-json

      - name: Check autograding.json
        run: ls -la .github/classroom/
        
      - name: Autograding
        uses: education/autograding@v1